#ifndef HEADER_CONFIG_MENDER_DEFINES_H
#define HEADER_CONFIG_MENDER_DEFINES_H

/* Shell variables */
#define MENDER_BOOT_PART_NUMBER 1
#define MENDER_BOOT_PART_NUMBER_HEX 1
#define MENDER_ROOTFS_PART_A_NUMBER 2
#define MENDER_ROOTFS_PART_A_NUMBER_HEX 2
#define MENDER_ROOTFS_PART_B_NUMBER 3
#define MENDER_ROOTFS_PART_B_NUMBER_HEX 3
#define MENDER_UBOOT_STORAGE_INTERFACE "mmc"
#define MENDER_UBOOT_STORAGE_DEVICE 2

/* Maveo variables. */
#define MENDER_STORAGE_DEVICE_BASE "/dev/mmcblk2p"
#define MENDER_UBOOT_ENV_STORAGE_DEVICE_OFFSET_1 0x100000
#define MENDER_UBOOT_ENV_STORAGE_DEVICE_OFFSET_2 0x110000
#define MENDER_ROOTFS_PART_A_NAME "/dev/mmcblk2p2"
#define MENDER_ROOTFS_PART_B_NAME "/dev/mmcblk2p3"

/* For sanity checks. */
#define MENDER_BOOTENV_SIZE CONFIG_ENV_SIZE

#define MENDER_BOOT_KERNEL_TYPE "bootz"
#define MENDER_KERNEL_NAME "zImage"
#define MENDER_DTB_NAME "/dtbs/imx6ull-maveo.dtb"
#define MENDER_UBOOT_PRE_SETUP_COMMANDS ""
#define MENDER_UBOOT_POST_SETUP_COMMANDS ""

#endif /* HEADER_CONFIG_MENDER_DEFINES_H */
